First
alexwti/java-filmorate pull request #1
Opened 2022-11-01 12:06 UTC by alexwti

2022-11-02 13:45 UTC, ErkinKasymaliev requested changes
отличная работа, но можно улучшить

2022-11-02 13:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping("/films")
правильно, что сразу там проставили path

2022-11-02 13:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
Некоторые if отсюда можно убрать, если в User/Film заюзать следующие аннотации:
@Size(min = , max =)
@Min(1)
@Email
Если прочитать про такие аннотации, то можно вообще без validate() обойтись, но это не точно)

коммент также для FilmController относится

2022-11-03 12:55 UTC, alexwti commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
Перевел на аннотации

2022-11-04 06:12 UTC, ErkinKasymaliev approved these changes
Отличная работа! принята

2022-11-04 06:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FilmReleaseDate.java
> +public @interface FilmReleaseDate {
красава!

2022-11-04 06:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +/*    public void validate(Film film) {
к следующему спринту удалите задокументированный код

2022-11-04 15:35 UTC, alexwti commented on src/main/java/ru/yandex/practicum/filmorate/annotation/FilmReleaseDate.java
> +public @interface FilmReleaseDate {
Спасибо!!!)))

2022-11-04 15:36 UTC, alexwti commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +/*    public void validate(Film film) {
Блин, забыл в горячке, исправлюсь)))

2022-11-04 15:37 UTC, alexwti commented
Closed

2022-11-11 12:54 UTC, merged