Add database
alexwti/java-filmorate pull request #4
Opened 2022-12-14 20:16 UTC by alexwti

2022-12-15 14:40 UTC, ErkinKasymaliev requested changes
Привет, оставил комменты.
И еще, почему удалили InMemoryFilmStorage.java и InMemoryUserStorage.java?
Их удалять нельзя. Смотрите @Quelifier в описании ТЗ

2022-12-15 14:40 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbFilmStorage.java
> +    private final GenreService genreService;
вот так делать нельзя. Вы можете инжектить стораджы в сервисы, но не наоборот. Поправьте везде где такое встречается

2022-12-15 14:40 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbFilmStorage.java
> +        final String sqlQuery = "SELECT * FROM FILMS WHERE FILM_ID = ?";
тут проверять не надо, так как 
 String sqlQueryUpd = "UPDATE FILMS SET FILM_NAME = ?, DESCRIPTION = ?, RELEASE_DATE = ?, DURATION = ?, RATING_ID = ? " +
                 "WHERE FILM_ID = ?";
         jdbcTemplate.update(sqlQueryUpd, ... возвращает число обновленных строк. Если вернет 0, то значит film_id нет. Отталкивайтесь от этого. Аналогично для остальных методов put в других storage-х

2022-12-15 14:40 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbFilmStorage.java
> +        return getById(film.getId());
возвращайте просто film; не надо делать лишнего запроса в бд

2022-12-15 14:40 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbUserStorage.java
> +        return getById(user.getId());
возвращайте просто user; не надо делать лишнего запроса в бд

2022-12-15 14:40 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbUserStorage.java
> +        final String sqlQuery = "SELECT * FROM USERS WHERE USER_ID = ?";
смотрите аналогичный комментв InDbFilmStorage

2022-12-15 15:22 UTC, alexwti commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbFilmStorage.java
> +        final String sqlQuery = "SELECT * FROM FILMS WHERE FILM_ID = ?";
Поправил

2022-12-15 15:22 UTC, alexwti commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbFilmStorage.java
> +        return getById(film.getId());
Поправил

2022-12-15 15:22 UTC, alexwti commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbUserStorage.java
> +        final String sqlQuery = "SELECT * FROM USERS WHERE USER_ID = ?";
Поправил

2022-12-15 15:24 UTC, alexwti commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbFilmStorage.java
> +    private final GenreService genreService;
А сторадж в сторадже? Иначе придется код дублировать(((

2022-12-15 15:54 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InDbFilmStorage.java
> +    private final GenreService genreService;
да, можно

2022-12-17 07:47 UTC, ErkinKasymaliev approved these changes
Работа принята

2022-12-19 14:29 UTC, merged